
clear all;
close all;
    
% Site information
site = ["Oznet";"GLDAS"];
depth = [3;4;15]; 
nstation = 38;

% read the format for the plots  
sig_abb = ["seasontrans_sdate_wet2dry_p"; "seasontrans_sdate_wet2dry_l"; ...
    "seasontrans_edate_wet2dry_p"; "seasontrans_edate_wet2dry_l"; ...
    "seasontrans_sdate_dry2wet_p"; "seasontrans_sdate_dry2wet_l"; ...
    "seasontrans_edate_dry2wet_p"; "seasontrans_edate_dry2wet_l"; ...
    "seasontrans_duration_wet2dry_p"; "seasontrans_duration_wet2dry_l"; ...
    "seasontrans_duration_dry2wet_p"; "seasontrans_duration_dry2wet_l"];

sig_abb2 = ["Wet end (p)"; "Wet end (l)"; ...
    "Dry start (p)"; "Dry start (l)"; ...
    "Dry end (p)"; "Dry end (l)"; ...
    "Wet start (p)"; "Wet start (l)"; ...
    "Wet to dry (p)"; "Wet to dry (l)"; ...
    "Dry to wet (p)"; "Dry to wet (l)"];

xline_format = ["--r"; "-r"; ...
                "--r"; "-r"; ...
                "--b"; "-b"; ...
                "--b"; "-b"];

% Color code 
% Dry2wet ... red
% Wet2dry ... blue 
% Piecewise ... break line 
% Logistic ... solid line
    
% align the seasonal transition and save into csv
% sig = stat_align(site, depth, nstation, sig_abb, sig_abb2)
stat_calc(site, depth, nstation, sig_abb, sig_abb2)

